### ISSUE TITLE
Check issue contents against issue template

### ISSUE THREAD

**Issue by stevenzeck** [stevenzeck/issue-check#5]
Keywords are great for those without an issue template, but would be better to match the issue body against the template itself.  This check would ensure the contents of the issue template are still there, but reporters would still be able to add the information being requested.

A common use case is having predefined "fields" in the template such as Operating System, OS Version, package version, etc.  We would want the text for those fields to still be present, but users would obviously be inputting the information requested.

- [ ] Config setting to turn on the check
- [ ] Catch errors if issue template can't be found
- [ ] Would probably override keywords, TBD
- [ ] Ensure there are no conflicts with tasklist completion

**Comment by Stanzilla** [comment]
Yes please
